### ISSUE TITLE
callback加密错误

### ISSUE THREAD

**Issue by southerncross** [hezedu/dd_suite_callback#1]
大哥，钉钉加密用的是suiteKey不是suiteId

![image](https://cloud.githubusercontent.com/assets/3861465/17690096/f02700d8-63be-11e6-8ddf-936e1272ec7d.png)

``` javascript
//suite4xxxxxxxxxxxxxxx 是钉钉默认测试suiteid  <-- 是key不是id
var newCrypt = new WXBizMsgCrypt(config.token, config.encodingAESKey, config.suiteid || 'suite4xxxxxxxxxxxxxxx');
```

被坑了一个周末啊，可把我害苦了啊，最后还是用官方java demo对着加密后的string一个一个对比才发现的

**Comment by hezedu** [comment]
之前的id就是key，我想应该是钉钉后台改版把我们坑了。已经加了注释提示了，多谢反馈。

**Comment by southerncross** [comment]
原来是这样。。
